### PR TITLE
Publish to WinGet

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
* https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/416
* https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/404

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@Klocman this one?

**Review by Klocman — COMMENTED** [review]
This action won't work without the secret token, and the version extraction I believe won't work correctly either. There's also no .exe filter to point at the installer.
Thank you for the PR, but it looks like I'll have to figure the whole process myself either way.

**Comment by vedantmgoyal2009** [comment]
You only have to create a GitHub Personal Access Token and store it as a repository secret.

The last two `0`s are appended to the version because the installer writes `5.4.0.0` to Apps and Features entries in Control Panel and not `5.4`. This is due to how the inno setup (.iss) installer is configured:

https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/d72788bcd01b109ff2d2aef59e5ca50e7ef397d4/installer/BcuSetup.iss#L8

https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/d72788bcd01b109ff2d2aef59e5ca50e7ef397d4/installer/BcuSetup.iss#L20

Also, the action automatically filters `.exe` files from GitHub Release assets.

**Comment by Klocman** [comment]
Alright, I took a look at how the action and overall winget update process works, looks like this should work. I'll give it a try.

**Comment by Klocman** [comment]
As I predicted the version extraction failed, so this release won't get automatically pushed to winget.
image
I fixed it here https://github.com/Klocman/Bulk-Crap-Uninstaller/commit/b3253f9b516e796dbb8f703cc853fdd3ba9903bf but it'll have to wait for the next release to be verified.

**Comment by sitiom** [comment]
- @Klocman Please see https://github.com/Klocman/Bulk-Crap-Uninstaller/pull/643

**Pull request merged**
