### PR TITLE
Add "Junk" removal switch to BCU-Console

### PR DESCRIPTION
**Pull request by nixuno**
Adds option for BCU-Console to perform junk removal with a `/J <Level>` switch. Includes updates to the documentation files to account for this change. Welcoming of any pointers or improvements that can be made.

I also included a change to `publish.bat` to use `vswhere.exe` to find `MSBuild.exe`. If this needs to be a separate PR I can split them out.

### CODE REVIEW

**Review by Klocman — CHANGES_REQUESTED** [review]
Overall the changes look good, but please move the msbuild path change into a separate PR.

It may be better to change `/J level` to `/J=level` so that a simple `string.Split` can be used instead of an error-prone index offset.

**Comment by goyalyashpal** [comment]
> It may be better to change `/J level` to `/J=level` so that a simple `string.Split` can be used instead of an error-prone index offset.

that is kinda new to me. as someone who's been using bash for over 2 yrs now, i never thought about this. 

* the space separation is always convenient to use though.
* it works _much much_ better when u are entering paths which can use the tab completion from shell

7-zip works the same way, `=` equals everywhere, which makes it suuuuuuper tedius to use due to lack of tab completions for paths.

but i guess it's just windows things - not aimed at CLI uses 🤷‍♀️😕

----

p.s. ohwwww, now i see why windows use backslashes for paths, 
'cz it reserves forward slashes for CLI options.
holy god. windows ssuckss big time each time.

**Comment by nixuno** [comment]
I made the requested reversion on the `publish.bat` file and changed the syntax to `/J=<Level>`. I did leave the option to just pass `/J` with no `=<Level>` which will default to a `VeryGood` confidence level.

**Review by Klocman — APPROVED** [review]
Looks good, thank you for the PR!

**Pull request merged**
